//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicsStatistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal
    {
        public int IdAthlete { get; set; }
        public int IdGame { get; set; }
        public int IdEvent { get; set; }
        public string Medal1 { get; set; }
    
        public virtual AthletesNF AthletesNF { get; set; }
        public virtual Event Event { get; set; }
        public virtual Game Game { get; set; }
    }
}
