//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicsEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class athlete
    {
        public long Id { get; set; }
        public Nullable<long> IdAthlete { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string NOC { get; set; }
        public string Games { get; set; }
        public Nullable<int> Year { get; set; }
        public string Season { get; set; }
        public string City { get; set; }
        public string Sport { get; set; }
        public string Event { get; set; }
        public string Medal { get; set; }
    }
}
