//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicsEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthletesNF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AthletesNF()
        {
            this.Medals = new HashSet<Medal>();
            this.Partecipations = new HashSet<Partecipation>();
        }
    
        public int IdAthlete { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medal> Medals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partecipation> Partecipations { get; set; }
    }
}
